config/routes.rb
PushItRealGood::Application.routes.draw do

  root :to => 'index#index'
  
  match 'user/:user' => 'page#user'
    
  resources :page
  
  match 'tally' => 'page#tally'
  
  devise_for :users #, :controllers => {:sessions => 'sessions'}
  
  match 'test_url' => 'page#check_for_url'
  match 'gallery' => 'page#list'
  match 'about' => 'page#about'
  match 'legal' => 'page#legal'
  match 'offensive' => 'page#offensive'
  match 'connect' => 'page#connect'
  match 'search' => 'utility#search'
  match 'retrieve_colors' => 'utility#get_buttons'
  
  match 'goodbyevincent' => 'vince#index'
  
  match 'admin' => 'admin#index'
  
  namespace :admin do
    resources :buttons
  end
  
end

app/models/Style.rb
class Style < ActiveRecord::Base
end

app/models/button.rb
class Button < ActiveRecord::Base
end

app/models/feature.rb
class Feature < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user
end

app/models/pages.rb
class Pages < ActiveRecord::Base
  belongs_to :user
end

app/models/site_info.rb
class SiteInfo < ActiveRecord::Base
end

app/models/styles.rb
class Styles < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pages
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  
  validates_presence_of :username
  validates_uniqueness_of :username
  
  def admin?
    self.role == "admin"
  end
  
  
    
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_filter :authenticate_user!, :admin?
  
  def index
    redirect_to '/users/sign_in'
  end
  
  def buttons 
    @styles = Style.find(:all)
    @buttons = Button.find(:all)
  end
  
  def new_button
    @style = Style.new
    @button = Button.new
  end
  
  def save_button
    @button = Button.new(params[:button])
    @button.save
    redirect_to("/admin/buttons")
  end
  
  def delete_button
    @button = Button.new(params[:button])
  end
  
  def destroy_button
    @button = Button.new(params[:button])
    @button.save
    redirect_to("/admin/buttons")
  end
  
  private
    def admin?
      if user_signed_in?
        if !current_user.admin?
          flash[:notice] = 'You do not have access to this section.'
          redirect_to('/users/sign_in')
        end
      end
    end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  before_filter :get_count
  
  def connect
    render :partial => 'connect'
  end
  
  def list 
    @count = Page.count
    @latest = Page.find(:all, :limit => 25, :order => "pages.created_at DESC" )
    @greatest = Page.find(:all, :limit => 25, :order => "pages.pushes DESC" )
    render :layout => 'application'
  end
  
  def check_for_url
    result = "pass"
    if Page.exists?( :title_url => params[:title_url] )
      result = "fail"
    elsif params[:title_url] == "new"
      result = "fail"
    end
    render :json => { "result" => result }
  end
  
  def show
    @page = Page.find(:first, :conditions => { "title_url" => params[:id] } )
    @user = User.find(:first, :conditions => { :id => @page.user_id })
    render :layout => 'page'
  end
  
  def user
    @user = User.find(:first, :conditions => { "username" => params[:user] })
    if @user
      @pages = Page.where(:user_id => @user.id)
      render :layout => 'application'
    else
      render :text => "No Such User, '#{params[:user]}'"
    end
  end
  
  def tally
    page = Page.find(:first, :conditions => { "title_url" => params[:id] } )
    unless page.increment!(:pushes)
      render :text => "Failed to tally push."
    end
    render :text => "Success."
  end
  
  def new
    @page = Page.new
    @options = Style.all.collect {|p| [ p.name.upcase, p.name.upcase ] }
    @action = params[:n]
    render :layout => 'application'
  end
  
  def create
    if Page.exists?( :title_url => params[:page][:title_url] )
      render :text => "This url is unavailable and somehow slipped past our validation"
    else
      @page = Page.new(params[:page])
      if @page.save
        flash[:notice] = "Successfully Created Page \"#{@page.title_url}\""
        redirect_to "/page/#{@page.title_url}"
      else
        render('new')
      end
    end
  end
  
  def offensive
    @page = Page.find(:first, :conditions => { :title_url => params[:id] } )
    
    if @page.update_attributes( :offensive => "true" )
    else
      render :text => "fail"
    end
    render :text => "success"
  end
  
  def save
    
  end
  
  def destroy
    @page = Page.find(params[:id]).destroy
    flash[:notice] = "Successfully Deleted Page."
    redirect_to "/gallery"
  end
  
  def about
    render :layout => 'application'
  end
  
  def legal 
    render :layout => 'application'
  end
  
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  
  before_filter :auth_soundcloud
  
  def show
    @track = @client.get('/resolve', :url => "http://soundcloud.com/festapush/ringtone-push-salt-n-pepa")
  end
  
  def search
    @tracks = @client.get('/tracks', :limit => "10", :q => params[:terms])
    @keyword = params[:terms]
  end

end

app/helpers/admin_helper.rb
module AdminHelper

  def iphone?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(iPhone|iPod|iPad)/]
  end

  def ie?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(MSIE)/]
  end

  def android?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(Android)/]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def iphone?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(iPhone|iPod|iPad)/]
  end
  
  def ie?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(MSIE)/]
  end
  
  def android?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(Android)/]
  end
  
  def admin?
    if user_signed_in?
      if !current_user.admin?
      end
    end
    return true
  end
  
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/page_helper.rb
module PageHelper
  
  def iphone?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(iPhone|iPod|iPad)/]
  end
  
  def ie?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(MSIE)/]
  end
  
  def android?
    request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(Android)/]
  end
  
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/utility_helper.rb
module UtilityHelper
end

app/helpers/vince_helper.rb
module VinceHelper
end

app/views/admin/index.html.erb
<%= link_to('New Button', {:action => 'new'}) %>

app/views/index/_features.html.erb
<div class="lower-content clearfix">
	
  <div class="top-ten clearfix">
	<h1>Popular Pushes</h1>
    <% @top_ten.each do |top_item| %>
	<div class="top-item">
	  <div class="button-image"><%= image_tag "/images/#{top_item.button_url}.png", :height => 40, :width => 80 %></div>
	  <div class="page-info">
	    <div class="user-page-url"><%= link_to top_item.title_url, "/page/#{top_item.title_url}" %></div> <div class="user-page-tagline">
		<% if top_item.pushes == 1 
		  	verbiage = "Push"
		   else
			verbiage = "Pushes"
		   end %>
	    <%= "#{top_item.pushes} #{verbiage}" %>
	 	
	    </div>
	  </div>
	  <div class="user-links">
		
	    <%= link_to "", "/page/#{top_item.title_url}", :class => "visit-btn" %>
		<% if user_signed_in? && admin? %>
		  <%= link_to "", top_item, :method => :delete, :class => "delete-btn", :confirm => "Are you sure you want to delete this page?" %>
		<% end %>
	  </div>
    </div>
    <% end %>
    <div class="gallery-link"><%= link_to "See The Gallery", "/gallery" %></div>
  </div>

  <div class="featured-button clearfix">
	
	<h1 class="featured-headline clearfix">Button of the Day</h1>
	<div class="random-button">
      <div class="push-it" id="push-it">
	    <a href="#" class="play no-underline" style="visibility:hidden" ><img src="/images/<%= @feature.button_url %>.png" alt="Button" class ="push-button" /></a>
	  </div>
	
	  <h1 class="featured-title clearfix"><%= link_to @feature.title_url, "/page/#{@feature.title_url}" %></h1>
	</div>
  </div>

<script type="text/javascript">

function prepNonFlash() {
  var clip = document.createElement('audio');
  clip.src = "<%= @feature.sound_url %>?client_id=72325d0b84c6a7f4bbef4dd86c0a5309";
  clip.load();
  clip.autobuffer = true;
  clip.preload = 'auto';
  $('.push-it').append(clip);
  $('.play').click( function(e) {
	e.preventDefault();
	clip.src = clip.src;
	clip.play();
  })
  $('.play').mousedown( function(e) {
	e.preventDefault();
	$(this).find('img').css("margin-left","-250px");
  })
  $('.play').mouseup( function(e) {
	e.preventDefault();
	$(this).find('img').css("margin-left","0");
  })
  $('.play').css("visibility","visible")
}

function prepFlash () {
  var swfVersionStr = "10.0.0";
  var xiSwfUrlStr = "playerProductInstall.swf";
  var flashvars = {};
  flashvars.streamURL = "<%= @feature.sound_url %>?client_id=72325d0b84c6a7f4bbef4dd86c0a5309";
  flashvars.imageURL = "/images/<%= @feature.button_url %>.png";
  flashvars.pageID = "<%= @feature.title_url %>"
  var params = {};
  params.quality = "best";
  params.wmode = "transparent";
  var attributes = {};
  swfobject.embedSWF("/swf/soundPlayer.swf", "push-it","250", "250", swfVersionStr, xiSwfUrlStr, flashvars, params, attributes);
}

if( $("body").hasClass( "iphone" ) ) {
  prepNonFlash();
} else {
  prepFlash();
}

</script>

</div>

app/views/index/index.html.erb
<div class="index-social clearfix">

	<div class="facebook-social">
	  <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fpushitrealgood.com&amp;send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=271596936217635" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:21px;" allowTransparency="true"></iframe>
	</div>

	<div class="twitter-social">
	  <a href="https://twitter.com/share" class="twitter-share-button" data-text="Sound + Button = Awesome. Create your own awesome at" data-count="horizontal">Tweet</a>
	  <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
	</div>
	
</div>

<div class="upper-content clearfix">
	
  <div class="logo-and-tagline clearfix">
		
    <div class="push-it-home">
      <img src="images/push-it-logo-beta.png" alt="Button" class="logo-button" />
    </div>

    <div class="three-steps">
      <div class="step-container clearfix"></div>
	  <script type="text/javascript">
	    var rand = Math.floor(Math.random() * (2));
	    if( rand > 0 ) $(".step-container").css("background-position","0 -224px")
	    $('.step-container').css("visibility","visible")
	    $('.step-container').click( toggle_hero )
	    function toggle_hero() {
		  if( $(".step-container").css("background-position") == "0px 0px" ) {
			$(".step-container").css("background-position","0 -224px")
		  } else if( $(".step-container").css("background-position") == "0px -224px" ) {
			$(".step-container").css("background-position","0 0")
		  }
	    }
	  </script>
    </div>

  </div>
  <div class="example">
    
    <div class="example-button">
	  <div class="push-it" id="push-it">
	    <a href="#" class="play no-underline" style="visibility: hidden;"><img src="/images/<%= @most_recent.button_url %>.png" alt="Button" class ="push-button" /></a>
	  </div>
	  <p class="featured-title clearfix">Most Recent: <%= link_to @most_recent.title_url, "/page/#{@most_recent.title_url}" %></p>
    </div>

    <div class="create-bar clearfix">
      <a href="/page/new" class="create-link"><span class="inner"></span></a>
      <a href="/gallery" class="gallery-link"><span class="inner">or Peep the Gallery</span></a>
    </div>
  </div>
</div>

<script type="text/javascript">

var count = <%= @most_recent.pushes %>;
function prepNonFlash() {
  var clip = document.createElement('audio');
  clip.src = "<%= @most_recent.sound_url %>?client_id=72325d0b84c6a7f4bbef4dd86c0a5309";
  clip.load();
  clip.autobuffer = true;
  clip.preload = 'auto';
  $('.push-it').append(clip);
  $('.play').click( function(e) {
	e.preventDefault();
	clip.src = clip.src;
	clip.play();
	tally();
  });
  $('.play').mousedown( function(e) {
	e.preventDefault();
	$(this).find('img').css("margin-left","-250px");
  });
  $('.play').mouseup( function(e) {
	e.preventDefault();
	$(this).find('img').css("margin-left","0");
  });
  $('.play').css('visibility','visible');
}

function prepFlash () {
  var swfVersionStr = "10.0.0";
  var xiSwfUrlStr = "playerProductInstall.swf";
  var flashvars = {};
  flashvars.streamURL = "<%= @most_recent.sound_url %>?client_id=72325d0b84c6a7f4bbef4dd86c0a5309";
  flashvars.imageURL = "/images/<%= @most_recent.button_url %>.png";
  flashvars.pageID = "<%= @most_recent.title_url %>"
  var params = {};
  params.quality = "best";
  params.wmode = "transparent";
  var attributes = {};
  swfobject.embedSWF("/swf/soundPlayer.swf", "push-it","250", "250", swfVersionStr, xiSwfUrlStr, flashvars, params, attributes);
  if( !$('body').hasClass('ie') ) document.getElementById("push-it").focus();
}

function tally() {
	count++;
	$('.count-numbers .numbers').empty().append(count);
	$('.count-numbers .numbers').css('width',$('.count-numbers .numbers').height());
	if( count == 1 ) {
	  $('.count-numbers .time').empty().append('Time');
	} else {
	  $('.count-numbers .time').empty().append('Times');
	}
}

if( $("body").hasClass( "iphone" ) )
{
	prepNonFlash();
} else {
	prepFlash();
}

</script>

app/views/layouts/_footer-nocount.html.erb
<footer>
    <nav>
      <ul class="clearfix">
		<li><a href="/wtf"><span class="inner single-line-link">What is this?</inner></span></a></li>
		<li><a href="/legal"><span class="inner single-line-link">Legal Terms</a></span></li>
		<li><a href="mailto:pusha@pushitrealgood.com"><span class="inner single-line-link">Contact Us</span></a></li>
      </ul>
    </nav>
  <div class="copyright">&#169; 2011 PUSH IT REAL GOOD</div>
</footer>

app/views/layouts/_footer.html.erb
<footer class="clearfix">
    <nav>
      <ul class="clearfix">		
		<li><a href="/about"><span class="inner single-line-link first">What is this?</span></a></li>
		<li><a href="/gallery"><span class="inner single-line-link">Gallery</span></a></li>
		<li><a href="/legal"><span class="inner single-line-link">Legal</span></a></li>
		<li><span class="inner single-line-link copyright">&#169; 2011 PUSH IT REAL GOOD</span></li>
		<li><span class="inner single-line-link footer-mckinney"><a href="http://mckinney.com" target="_blank">created by <%= image_tag "/images/mckinney-logo-small.png" %></a></span></li>
		<li><span class="inner single-line-link footer-powered-by last"><a href="http://soundcloud.com" target="_blank">powered by <%= image_tag "/images/soundcloud-logo-small.png" %></a></span></li>
		
      </ul>
    </nav>
</footer>

app/views/layouts/_menubar-ajax.html.erb
  <div class="nav_bar clearfix">
	<div class="social-buttons">
	  <div class="facebook-button">
	    <div id="fb-root"></div>	  
	    <div class="fb-like" data-href="http://pushitrealgood.com" data-send="false" data-layout="button_count" data-width="90" data-show-faces="true" data-font="arial"></div>
	  </div>
	  <div class="twitter-button">
	    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://pushitrealgood.com" data-text="Choose a sound. Choose a button. Share anytime. Push It Real Good." data-count="horizontal">Tweet</a>
	  </div>
	  <div class="google-button">
	    <div class="g-plusone" data-size="medium" data-href="http://pushitrealgood.com"></div>
	  </div>
	</div>
	<div class="session_status">
      <% if user_signed_in? %>
        Logged in as <span class="username"><%= current_user.username %></span>. Go to my <%= link_to "profile", "/user/#{current_user.username}" %> 
		Not you? <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
      <% else %>
		<div><%= label_tag :username, "Username" %><br />
	    <%= text_field_tag :username %></div>

	    <div><%= label_tag :password, "Password" %><br />
	    <%= password_field_tag :password %></div>
        <%= link_to "Login", new_user_session_path, :class => "login-button" %>
		<%= link_to "Sign Up", new_user_registration_path, :class => "sign-up-button" %>
	  <% end %>
    </div>
  </div>
<script type="text/javascript">

// Set up CSRF token to work with AJAX
var csrf_token = $('meta[name=csrf-token]').attr('content');

$("body").bind("ajaxSend", function(elm, xhr, s){
   if (s.type == "POST") {
      xhr.setRequestHeader('X-CSRF-Token', csrf_token);
   }
});

function login() {
  var email = $('#username').val();
  var password = $('#password').val();
  var data = {remote: true, commit: "Sign in", utf8: "✓",headers: {'Content-Type': 'application/json'},
              user: {remember_me: 1, password: password, email: email}};
  $.post('/users/sign_in.json', data, function(resp) {
    if(resp.success) {
      // process success case
	  console.log("sign in success");
    } else {
      // let the user know they failed authentication
	  console.log("sign in failure");
    }
  });
  return false;
}

$('.login-button').click( function(e) {
	e.preventDefault();
	login();
})
</script>





  <script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) {return;}js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";fjs.parentNode.insertBefore(js, fjs);}(document, 'script','facebook-jssdk'));</script>
  <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
  <script type="text/javascript">(function(){var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;	      po.src = 'https://apis.google.com/js/plusone.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);})();</script>

app/views/layouts/_menubar-nosocial.html.erb
  <div class="nav_bar clearfix">
	<div class="session_status">
      <% if user_signed_in? %>
        Logged in as <span class="username"><%= current_user.username %></span>. Go to my <%= link_to "profile", "/user/#{current_user.username}" %> 
		Not you? <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
		<%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
  </div>

app/views/layouts/_menubar.html.erb
  <div class="nav_bar clearfix">
	<div class="session_status">
      <% if user_signed_in? && admin? %>
        Logged in as admin <span class="username"><%= current_user.username %></span>. <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
		<%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
  </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Push It Real Good -- Create your own one-button-site. -- Admin</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="<%= root_path %>stylesheets/base.css" type="text/css" />
  <link rel="stylesheet" href="<%= root_path %>stylesheets/main.css" type="text/css" />
  <link rel="stylesheet" href="<%= root_path %>stylesheets/admin.css" type="text/css" />
  <link rel="shortcut icon" type="image/x-icon" href="<%= root_path %>images/favicon.ico" />
  <%= javascript_include_tag "application" %>
  <script src="/js/jquery-1.6.4.min.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
  <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="<%= (iphone?) ? 'iphone' : '' %> <%= (android?) ? 'android' : '' %> <%= (ie?) ? 'ie' : '' %>">

<div class="wrapper">
	
  <%= render "layouts/menubar" %>
  
  <div class="content">

    <%= yield %>

  </div> <!-- content -->

</div> <!-- wrapper -->

<footer>
  <nav>
    <ul>
      <li><%= link_to "What is PIRG?", "/wtf" %></li>
      <li><%= link_to "Legal Terms", "/legal" %></li>
      <li><%= link_to "Contact Us", "mailto:pusha@pushitrealgood.com" %></li>
      <li>&#169; 2011 PUSHITREALGOOD</li>
    </ul>
  </nav>
</footer>

</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24443364-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Push It Real Good -- Create your own one-button-site.</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="<%= root_path %>stylesheets/base.css" type="text/css" />
  <link rel="stylesheet" href="<%= root_path %>stylesheets/main.css" type="text/css" />
  <link rel="stylesheet" href="<%= root_path %>stylesheets/jquery.jscrollpane.css" type="text/css" />
  <link rel="stylesheet" href="<%= root_path %>stylesheets/jquery.selectBox.css" type="text/css" />
  <link rel="shortcut icon" type="image/x-icon" href="<%= root_path %>images/favicon.ico" />
  <!--[if lt IE 9]>
  <link rel="stylesheet" type="text/css" href="<%= root_path %>stylesheets/ie.css" />
  <![endif]-->
  <%= javascript_include_tag "application" %>
  <script src="/js/jquery-1.6.4.min.js" type="text/javascript"></script>
  <script src="/js/jquery.use.min.js" type="text/javascript"></script>
  <script src="/js/swfobject.js" type="text/javascript"></script>
  <meta property="og:url" content="http://pushitrealgood.com" />
  <meta property="og:title" content="Push It Real Good" />
  <meta property="og:image" content="http://pushitrealgood.com/images/push-it-logo-small.png" />
  <meta property="og:description" content="Sound + Button = Awesome. Create your own Awesome — share it with the world." />
  <meta itemprop="name" content="Push It Real Good">
  <meta itemprop="description" content="Sound + Button = Awesome. Create your own Awesome — share it with the world.">
  <meta itemprop="image" content="http://pushitrealgood.com/images/push-it-logo-small.png">
  <meta name="viewport" content="maximum-scale=1,user-scalable=yes,width=1000" />
  <!--[if lt IE 9]>
  <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  
</head>
<body class="<%= (iphone?) ? 'iphone' : '' %> <%= (android?) ? 'android' : '' %> <%= (ie?) ? 'ie' : '' %> <%= @action %>">
	
<div class="wrapper">
	
  <% if user_signed_in? && admin? %>
    <%= render "layouts/menubar" %>
  <% end %>
	
  <div class="content" id="content">
	
    <%= yield %>

  </div> <!-- content -->
	
  <%= render "layouts/footer" %>

</div> <!-- wrapper -->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24443364-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

app/views/page/_info.html.erb
	<div class="info-bar">
		
	  <div class="info-buttons">
		<span class="info-button-span mini-logo-container"><%= link_to  "Home", root_path %></span>
		<span class="info-button-span "><%= link_to "Create", "/page/new" %></span>
      </div>

    </div>

app/views/page/user.html.erb
<%= link_to "", root_path, :class => "small-logo" %>
<div class="user-info">
<% if @user == current_user %>
  <% title =  "Welcome Back, #{current_user.username}!" %>
<% else %>
  <% title = "This is #{@user.username}." %>
<% end %>

<div class="user-bar clearfix">
  <h1 class="whose-pages"><%= title %></h1>
  <div class="user-bar-border"></div>
  <% if @user == current_user %>
  <p class="new-page"><%= link_to "", new_page_path %></p>
  <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %>
  <% end %>
  <div class="join-date"><div class="date-joined"><%= @user.created_at.strftime("%m/%d/%Y") %></div><div class="member-since">Member<br/>Since</div> </div>
  <div class="num-pages"><div class="page-amt"><%= @pages.count %></div> <div class="pages-made">Pages<br/>Made</div></div>
</div>

<div class="pages">
<% if flash[:warning] or flash[:notice] %>
  <p class="notice"><%= flash[:notice] %> <%= image_tag "/images/kill-notice.png" %></p>
<% end %>
<% @pages.each do |page| %>
<div class="page clearfix">
  <div class="button-image"><%= image_tag "/images/#{page.button_url}.png", :height => 40, :width => 80 %></div>
  <div class="page-info">
    <div class="user-page-url"><%= link_to page.title_url, "/page/#{page.title_url}" %></div> <div class="user-page-tagline"><%= page.tagline %></div>
  </div>
  <div class="user-links">
    <%= link_to "", "/page/#{page.title_url}", :class => "visit-btn" %>
    <% if @user == current_user %>
      <%= link_to "", "#", :class => "edit-btn"  %>
      <%= link_to "", page, :method => :delete, :class => "delete-btn", :confirm => "Are you sure you want to delete this page?" %>
    <% end %>
  </div>
</div>
<% end %>
</div>
</div>

<script type="text/javascript" src="/js/user-profile.js"></script>